### ISSUE TITLE
Implement native Auto-Coloring for Odd/Event rows

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#224] opened 2015-01-21 13:44 UTC
_From [winkelsdorf](https://code.google.com/u/winkelsdorf/) on July 07, 2011 22:12:08_

I suggest implementing the well-known Odd/Even coloring of rows natively into VTV (already known back in the VTV yahoo groups days).

A simple published property together with a slight change in the DoBeforeItemErase:

procedure TVirtualTreeEx.DoBeforeItemErase(Canvas: TCanvas; Node: PVirtualNode;
  ItemRect: TRect; var Color: TColor; var EraseAction: TItemEraseAction);
begin
  inherited;
  if FAutoColorRows then
  begin
    // color every 2nd row in grid
    // Attn: Do not use Self.AbsoluteIndex(Node) here - it is far too slow
    if Odd(Node.Index) then
    begin
      Color := clInfoBk;
      EraseAction := eaColor;
    end;
  end;
end;

A further possibility would be to allow the user to set the highlight color and whether to highlight the Odd OR Even rows.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=224_

**Comment by vincentparrett** [comment] 2015-01-21 13:44
_From [john.rep...@gmail.com](https://code.google.com/u/105273605677069700234/) on July 08, 2011 07:32:48_

It might be interesting to extend the above suggestion to every nth set of rows.
example: every set of 5 rows would change color, etc...

**Comment by vincentparrett** [comment] 2015-01-21 13:44
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on June 10, 2012 23:24:03_

**Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment] 2015-01-21 13:45
_From [fr0st.br...@gmail.com](https://code.google.com/u/108120151676755512560/) on October 15, 2012 00:50:26_

Implemented
Zebra line painting (odd and even lines could be filled with different background color)
Added: toZebraLines value to TVTPaintOption
       OddLineColor, EvenLineColor fields to TVTColors

Apply this patch or check my fork at https://github.com/Fr0sT-Brutal/VirtualTreeView_mod

**Attachment:** [0218-Fr0sT-mod.patch](http://code.google.com/p/virtual-treeview/issues/detail?id=224#hc3)

**Comment by joachimmarder** [comment] 2015-03-25 20:27
Since we are at GitHub now, can you make a pull request please?

**Comment by sglienke** [comment] 2015-12-07 14:12
The proposed solution does not work with filtering since you cannot simply take the Node.Index as indicator.

**Comment by Fr0sT-Brutal** [comment] 2019-07-16 14:01
> Since we are at GitHub now, can you make a pull request please?

As Stefan noted, this will work only if no filtering happened so IMHO it would be a feature with hidden and unexpected behavior. I'm not sure if such a feature should be added.
Unless we have fast built-in VisibleIndex property, this feature (I call it zebra paint) will only work in some special conditions.

**Comment by joachimmarder** [comment] 2021-04-11 16:16
After almost 10 years without a pull request or a fix, I am closing this issue as "WontDo". Pull request can still be sent.

**Closed as completed by joachimmarder** 2021-04-11 16:16 UTC
Labels: Enhancement, Pull Requests Invited, WontDo

**Comment by Fr0sT-Brutal** [comment] 2021-04-12 07:19
There are two patches. It's rather zero will of maintainers...

**Comment by sglienke** [comment] 2021-04-12 10:00
> There are two patches. It's rather zero will of maintainers...

Are you referring to the patches that use node.Index? We agreed they don't work.
If there are others I cannot see them in this conversation
