### ISSUE TITLE
HintMode hmHintAndDefault: If the default hint is shown and you move over a node the node specific hint is not shown unless you leave the VT control

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#289] opened 2015-01-21 13:48 UTC
_From [roth_...@web.de](https://code.google.com/u/111079903701973761991/) on September 25, 2012 20:14:46_

What steps will reproduce the problem? 1. Set HintMode to hmHintAndDefault
2. Move mouse over an area where there is no node
3. The default hint of the control is shown
4. Move mouse over a node (wihtout leaving the VT control) What is the expected output? What do you see instead? No node specific hint is shown. What version of the product are you using? On what operating system? 4.8.6 Please provide any additional information below.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=289_

**Comment by vincentparrett** [comment] 2015-01-21 13:48
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on October 22, 2012 01:26:25_

V4.8.6 is outdated. Can you please try V5.0.1?

**Owner:** joachim....@gmail.com

**Comment by vincentparrett** [comment] 2015-01-21 13:49
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on November 02, 2012 02:59:58_

OK, the problem also exists in the current version.

**Comment by vincentparrett** [comment] 2015-01-21 13:49
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 31, 2012 06:05:07_

I used the "Advanced" demo project to replicate this behavior. I used the page with property grid (third page), and set the Hint property to "VTV" and the HintMode to hmHintAndDefault. When the control hint is shown, it is not reliably hidden when the user moves the mouse insice the VTV-control.

**Status:** Accepted

**Comment by sanjayssk** [comment] 2016-11-22 08:36
I can't reproduce this problem. I remember working on issue #623 for hints where I discovered some cases where a node specific hint may not be produced and commented accordingly. I also made changes to properties unit then. Can that be the reason? I will try reproducing the problem in some other unit too.

**Comment by joachimmarder** [comment] 2016-11-22 09:41
The last comments are nearly 4 years old. It is not unlikely the problem has been fixed meanwhile. We can then close this issue.

**Comment by sanjayssk** [comment] 2016-11-22 12:24
I will confirm once more with another vtv from the demo and then close.

Thanks.

**Comment by sanjayssk** [comment] 2016-11-25 16:53
Found the reason why I could not reproduce the problem. This problem appears only if the columns do not occupy the full client area. This demo seems to have been modified with hoAutoResize so that the columns take up full client area. Hence, I was not seeing the problem. When I switched off the above option, I saw the problem.

**Closed as completed** 2016-11-26 16:33 UTC
Labels: Bug
