### ISSUE TITLE
Node text is unnecessarily shortened (with triple dot ellipsis) in 'TCustomVirtualStringTree.PaintNormalText'

### ISSUE THREAD

**Issue by DanielBauten** [JAM-Software/Virtual-TreeView#1077] opened 2022-01-12 10:00 UTC
### Problem

In some cases (single-line) node text is unnecessarily shortened (with triple dot ellipsis) in `TCustomVirtualStringTree.PaintNormalText`. This occures when `FFontChanged` is `True` after calling `DoPaintText`. Then resetting the width of the ellipsis string (for later recalculation) is necessary. But recalculating `NodeWidth` by calling WinAPI function `GetTextExtentPoint32W` (see [here](https://github.com/JAM-Software/Virtual-TreeView/blob/abbbdf89e2d5befca8519e1622a31fc8193f621a/Source/VirtualTrees.pas#L24687)) (sometimes) results in an erroneous off-by-one width, that is one pixel greater than already correctly calculated before by calling `DoPaintText` and `DoTextMeasuring` in `TCustomVirtualStringTree.CalculateTextWidth`. Thus, the actually fitting text will be shortened afterwards.

### Suggested solution

As the text width is already correctly calculated with consideration of the corresponding custom font, recalculating `NodeWidth` is not necessary in any case and should be removed.

**Comment by DanielBauten** [comment] 2022-01-12 10:22
Maybe this also fixes #465.

**Comment by joachimmarder** [comment] 2022-01-12 14:32
> already correctly calculated before by calling DoPaintText and DoTextMeasuring

I don't see why the `NodeWidth` should be already calculated. Only `DoPaintText()` is guaranteed to be called. The event handler assigned to `OnPaintText` may eventually change the font which causes `FFontChanged` to be `True` and the removed code you suggest to be removed executed.  Where / how is `DoTextMeasuring()` called in this scenario?

Are you able to supply a small sample project (or change one of the existing) so that the problem and the fix can be verified?

**Comment by hermannoffen** [comment] 2022-01-17 09:22
The relevant execution tree looks like this (line numbers based on [`master` @ `abbbdf`](https://github.com/JAM-Software/Virtual-TreeView/blob/abbbdf89e2d5befca8519e1622a31fc8193f621a/Source/VirtualTrees.pas)):
```
…
└── `TBaseVirtualTree.PaintTree`
    ├── `TCustomVirtualStringTree.DoGetNodeWidth` (called from line 22280; return value is assigned to `PaintInfo.NodeWidth`)
    │   └── `TCustomVirtualStringTree.CalculateTextWidth` (called from line 25082 or 25091)
    │       ├── `TCustomVirtualStringTree.DoPaintText` (called from line 24963)
    │       └── `TCustomVirtualStringTree.DoTextMeasuring` (called from line 24965)
    └── `TCustomVirtualStringTree.DoPaintNode` (virtually called from line 22404 *_exclusively_*)
        └── `TCustomVirtualStringTree.PaintNormalText` (called from line 25170 *_exclusively_*)
            └── `TCustomVirtualStringTree.DoPaintText` (esp. called from line 24682)
```

So, `PaintInfo.NodeWidth` is always initialized before `PaintNormalText` is executed.
If the `FOnPaintText` event method called from `DoPaintText` changed the `Font`, it would have done it on the first call, too.
That would have been considered in `DoTextMeasuring` then. Thus, imho, there's no need to recalculate text width in any case.
Furthermore, it seems smelly to me that we are recalculating text width not using the designated methods `CalculateTextWidth` or `DoTextMeasuring`.

I was able to reproduce the problem in the _Advanced_ demo with a few changes. It looks like `GetTextExtentPoint32W` is insufficient when using custom drawing and leads to incorrect measurement.

Extension as patch:
```
diff --git a/Demos/Advanced/GeneralAbilitiesDemo.pas b/Demos/Advanced/GeneralAbilitiesDemo.pas
index 8559e3a5dd63738ec199f8f897e0573b18b48303..0909aab272878710ac6256e951d6138779acfb74 100644
--- a/Demos/Advanced/GeneralAbilitiesDemo.pas
+++ b/Demos/Advanced/GeneralAbilitiesDemo.pas
@@ -83,6 +83,12 @@ type
       var Ghosted: Boolean; var ImageIndex: TImageIndex;
       var ImageList: TCustomImageList);
     procedure VST2FreeNode(Sender: TBaseVirtualTree; Node: PVirtualNode);
+    procedure VST2MeasureTextWidth(Sender: TBaseVirtualTree;
+      TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
+      const Text: string; var Extent: Integer);
+    procedure VST2DrawText(Sender: TBaseVirtualTree; TargetCanvas: TCanvas;
+      Node: PVirtualNode; Column: TColumnIndex; const Text: string;
+      const CellRect: TRect; var DefaultDraw: Boolean);
   end;
 
 var
@@ -177,7 +183,14 @@ begin
     1: // image column (there is no text)
       ;
     2: // language column (no customization)
-      ;
+      if TextType = ttNormal then
+        with TargetCanvas.Font do
+        begin
+          Name  := 'Segoe UI';
+          Color := clRed;
+          Size  := 11;
+          Style := [fsBold];
+        end;
   end;
 end;
 
@@ -205,6 +218,37 @@ begin
   else
     E.CellText := '';
   end;
+
+
+  if E.Column = 2 then
+    E.CellText := '1,0 AT';
+end;
+
+function CustomDrawText(TargetCanvas: TCanvas;
+  const Text: String; Rect: TRect; const AdditionalDrawFlags: UINT): Integer;
+begin
+  DrawTextW(TargetCanvas.Handle, PWideChar(Text), Length(Text),
+            Rect, DT_NOPREFIX or AdditionalDrawFlags);
+  Result := Rect.Right - Rect.Left;
+end;
+
+procedure TGeneralForm.VST2DrawText(Sender: TBaseVirtualTree;
+  TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
+  const Text: string; const CellRect: TRect; var DefaultDraw: Boolean);
+begin
+  if Column = 2 then
+  begin
+    CustomDrawText(TargetCanvas, Text, CellRect, DT_RIGHT);
+    DefaultDraw := False;
+  end;
+end;
+
+procedure TGeneralForm.VST2MeasureTextWidth(Sender: TBaseVirtualTree;
+  TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex;
+  const Text: string; var Extent: Integer);
+begin
+  if Column = 2 then
+    Extent := CustomDrawText(TargetCanvas, Text, Rect(0, 0, 0, 0), DT_RIGHT or DT_CALCRECT);
 end;
 
 //----------------------------------------------------------------------------------------------------------------------
diff --git a/Demos/Advanced/GeneralAbilitiesDemo.dfm b/Demos/Advanced/GeneralAbilitiesDemo.dfm
index ba8211dca3107a4df5ecf3c48d5141fab6262f40..59e2a55e62f567c83ddbd37c7b40f122c273239f 100644
--- a/Demos/Advanced/GeneralAbilitiesDemo.dfm
+++ b/Demos/Advanced/GeneralAbilitiesDemo.dfm
@@ -64,6 +64,7 @@ object GeneralForm: TGeneralForm
     TreeOptions.SelectionOptions = [toExtendedFocus, toMiddleClickSelect, toMultiSelect, toRightClickSelect]
     TreeOptions.StringOptions = [toSaveCaptions, toShowStaticText, toAutoAcceptEditChange]
     OnDragOver = VST2DragOver
+    OnDrawText = VST2DrawText
     OnFocusChanging = VST2FocusChanging
     OnFreeNode = VST2FreeNode
     OnGetCellText = VST2GetCellText
@@ -74,6 +75,7 @@ object GeneralForm: TGeneralForm
     OnInitChildren = VST2InitChildren
     OnInitNode = VST2InitNode
     OnKeyDown = VST2KeyDown
+    OnMeasureTextWidth = VST2MeasureTextWidth
     OnNewText = VST2NewText
     OnStateChange = VST2StateChange
     Columns = <
```

**Comment by joachimmarder** [comment] 2022-01-19 14:40
Sorry, I missed that `DoPaintNode()` is called exclusively from `PaintTree()`. Then it makes sense.

**Closed as completed** 2022-01-19 14:41 UTC
Labels: Bug
