### ISSUE TITLE
If BidiMode=RightToLeft Header not draw

### ISSUE THREAD

**Issue by cirtasoft** [JAM-Software/Virtual-TreeView#544] opened 2015-04-28 21:55 UTC
![bidimode](https://cloud.githubusercontent.com/assets/12158881/7381283/c12c70ba-edf9-11e4-8b08-487951afc2ee.PNG)
Hello,

I have try change bidimode to right to left and header not draw.

joint photo

**Comment by cirtasoft** [comment] 2015-04-28 22:16
Hello,

I have find the solution, is bug in your source.

change to :

```
// Now go for each button.
if Self.FHeader.FOwner.BiDiMode = bdRightToLeft then
  while (Run > NoColumn) do
  begin
    TargetRect.Right := TargetRect.Left + Items[Run].FWidth;
    //TargetRect.Right := TargetRect.Left;
    //TargetRect.Left := TargetRect.Left - Items[Run].FWidth;

    // create a clipping rect to limit painting to button area
    ClipCanvas(TargetCanvas, Rect(TargetRect.Left, Target.Y + R.Top,
                                  TargetRect.Right, TargetRect.Bottom));

    PaintColumnHeader(Run, TargetRect);

    SelectClipRgn(Handle, 0);

    TargetRect.Left := TargetRect.Right;
    Run := GetNextVisibleColumn(Run)
  end
else
  while (Run > NoColumn) and (TargetRect.Left < MaxX) do
  begin
    TargetRect.Right := TargetRect.Left + Items[Run].FWidth;

    // create a clipping rect to limit painting to button area
    ClipCanvas(TargetCanvas, Rect(Max(TargetRect.Left, Target.X), Target.Y + R.Top,
                                  Min(TargetRect.Right, MaxX), TargetRect.Bottom));

    PaintColumnHeader(Run, TargetRect);

    SelectClipRgn(Handle, 0);

    TargetRect.Left := TargetRect.Right;
    Run := GetNextVisibleColumn(Run)
  end;
```

**Comment by joachimmarder** [comment] 2015-04-29 07:59
Could this be a duplicate of #427?
Which version of Virtual TreeView do you use?
Are you able to send a pull request or a patch file?

**Comment by sanjayssk** [comment] 2016-07-20 06:08
Rather than the code suggested, the solution involves offsetting MaxX correctly based on BidiMode. Done and tested.

**Closed as completed by sanjayssk** 2016-07-20 06:08 UTC
Labels: Bug, Pull Requests Invited
