### ISSUE TITLE
F2084 Internal Error: URW1147

### ISSUE THREAD

**Issue by zuobaoquan** [JAM-Software/Virtual-TreeView#1167] opened 2023-01-28 02:28 UTC
The following fatal error occurred when compiling the latest V8 code in XE3-XE7

`[dcc32 Fatal Error] VirtualTrees.pas(1934): F2084 Internal Error: URW1147`

**Comment by joachimmarder** [comment] 2023-01-28 16:20
Does the official release V7.6.3 still work for you?

This is most likely a bug in the compiler fixed in a later version, not a bug in Virtual TreeView.

**Comment by zuobaoquan** [comment] 2023-01-29 01:22
Yes, it is definitely a compiler bug. I reported it as the minimum supported version of V8 is XE3, isn't it?

The bug doesn't occur even with the commit f07a7416cc857330342ad6994cad9941365641cb (Dec 14th, 2022)

**Comment by zuobaoquan** [comment] 2023-01-29 01:37
P.S. I need to support XE3-11 for IDE plugins, so I prefer a single version of VirtualTreeView.

**Comment by joachimmarder** [comment] 2023-01-29 14:29
> I reported it as the minimum supported version of V8 is XE3, isn't it?

Well, I never really made a decision regarding this, but I was thinking about dropping the support for some older versions for V8, as it is getting more and more challenging to maintain such so many versions of Delphi. I can try to maintain compatibility regarding the used language and VCL features, but it's getting difficult when it is coming to compiler bugs.

> I need to support XE3-11 for IDE plugins, so I prefer a single version of VirtualTreeView.

In this case please use V7.

**Comment by joachimmarder** [comment] 2023-01-29 14:47
> the bug doesn't occur even with the commit https://github.com/JAM-Software/Virtual-TreeView/commit/f07a7416cc857330342ad6994cad9941365641cb

Well, this commit just introduces some conditional code. I need conditional code to support older versions of Delphi, but if the use of these conditionals causes internal compiler errors, then it's getting tricky.

**Comment by joachimmarder** [comment] 2023-05-09 19:32
I am closing this issue as this is a compiler bug. Please feel free to send workarounds as a pull request anyway.

**Closed as completed by joachimmarder** 2023-05-09 19:32 UTC
Labels: Pull Requests Invited, Not our issue
