### ISSUE TITLE
Overlapping of Nodes in VT

### ISSUE THREAD

**Issue by luedech** [JAM-Software/Virtual-TreeView#594] opened 2015-12-03 15:44 UTC
due to some mouse-action Virtualtreeview Shows overlapped nodes
![overlappednodes](https://cloud.githubusercontent.com/assets/16137388/11565120/d7956a98-99dc-11e5-9e56-53f5b0d9bacf.jpg)
first monitored with version 5.3

**Comment by joachimmarder** [comment] 2015-12-05 10:30
Are you able to provide a simple project that allows to replicate the problem?
One of the Virtual TreeView demo projects modified to show this issue would be helpful too
.
Are you using custom drawing?

> first monitored with version 5.3

So V5.2.2 did not show this behavior?
Are you able to identify the exact revision that introduced the issue?

**Comment by luedech** [comment] 2015-12-21 11:19
I have done some tests with two Delphi versions. It seems to be a problem with used Delphi version. Application compiled with Delphi 2010 and VT 5.3 - no problems occurs until now. The same source code of VT Version 5.3 compiled with Delphi XE7 the problem as described occurs after a short time.

Maybe it ‘s an issue of upgrading source code?

**Comment by joachimmarder** [comment] 2015-12-21 11:47
Are you able to provide a simple project that allows to replicate the problem?
One of the Virtual TreeView demo projects modified to show this issue would be helpful too.

Are you using custom drawing?

**Comment by luedech** [comment] 2015-12-21 14:52
Thank you for your response. 
I am not using custom drawing but I am using VT on TFrames. And perhaps that could be  a (the) problem. When I upgraded from Delphi 2010 to Delphi XE7 some events of VT don't work properly anymore. (for example onpopup) The solution was that I have to move the onevent-functions from VT on Tframe to the VTs on mainform (childframe).
Could it be in that case mouse events are sometimes ignored or misinterpreted? 
Trigger of this is always a mouse-click.

Today I tested it with Demo-VT "Advanced VT" - never occured. But my application with Frames Shows after some mouse-clicks - overlapping nodes.

**Comment by joachimmarder** [comment] 2015-12-21 18:46
Frames in Delphi are known to be buggy, so this could be one reason for this problem to occur.

Typically issues with frames got better and not worse with new versions of Delpgi, but maybe something goes wrong when the project / DFM is upgraded to the new version.

The "Advanced" sample project uses re-parented forms as children, and no frames. You may consider this as well if it fits your project.

Without steps to reproduce the problem there is not much I can do about this. We had no similar reports so far.

**Comment by joachimmarder** [comment] 2016-01-06 17:44
Were you able to identify the reason for these problems or find steps for reproducing the issue?

**Comment by luedech** [comment] 2016-01-07 08:01
In the last few days I worked hard in my application to change frames to re-parented forms as children. (under Delphi XE7 - similar to the Advanced Demo Project VT) After some tests unfortunately the problem still occured. For now I can only say that compiled with Delphi 2010 - everything is good, compiled with Delphi XE7 the problem comes again. Trigger is always a mouse click (after an undefined time). I will further look for possible reasons for this problem.

**Comment by joachimmarder** [comment] 2016-02-28 21:11
Sorry, but if there are no similar reports and no repro, I will close this issue in a few weeks to keep the list clean.

**Closed as completed** 2016-04-05 21:08 UTC

**Comment by joachimmarder** [comment] 2017-03-02 12:54
This problem only occurs when using VCL styles. It is still present in 10.1 Berlin. It occurs on slow machines only. There are still no repro steps.
