### ISSUE TITLE
Add OnChanging event

### ISSUE THREAD

**Issue by Tetram76** [JAM-Software/Virtual-TreeView#671] opened 2016-11-15 08:48 UTC
There's an OnFocusChanging event allowing to lock focusednode but no OnChanging event to lock selectednode.

I think such event would be the most obvious way to avoid user to change the current selection in some conditions.

**Comment by joachimmarder** [comment] 2016-11-15 21:04
This is a duplicate of #635

**Closed as completed by joachimmarder** 2016-11-15 21:04 UTC
Labels: Duplicate
