### ISSUE TITLE
VCL Themes: Basic TVirtualStringTree Colors does not apply

### ISSUE THREAD

**Issue by sinys5** [JAM-Software/Virtual-TreeView#593] opened 2015-12-02 17:41 UTC
Delphi Seattle, Virtual-TreeView 6.2.1
I have project with Obsidian VCL theme.
This theme has yellow color for selected node, but I want return color for selected node to basic and I wrote this code:
  TreeView.StyleElements := TreeView.StyleElements - [seFont, seClient];
  TreeView.Colors.FocusedSelectionColor := clHighlight;
  TreeView.Colors.FocusedSelectionBorderColor := clHighlight;
  TreeView.Colors.SelectionRectangleBlendColor := clHighlight;
  TreeView.Colors.SelectionRectangleBorderColor := clHighlight;
  TreeView.Colors.HotColor := clHighlight;
  TreeView.Colors.SelectionTextColor := clBlack;

But it doesn't work, selected node still have yellow color.
Is it a bug or I did something wrong?

**Comment by joachimmarder** [comment] 2015-12-02 21:54
So far this is by design, we tried to make the behavior as similar to the standard VCL components as possible. The StyleElements property does not have a dedicated flag for the selection, so styles have priority here if activated.

We could now discuss if TStyleElements.seClient should have an effect on the drawing of the selection etc. 

In any case you can custom draw the selection or tweak TVTColors.GetColor() in your copy.

**Comment by joachimmarder** [comment] 2015-12-02 22:02
I think I found a good solution for this case, which I just committed.

**Closed as completed** 2015-12-02 22:03 UTC
Labels: Bug
