### ISSUE TITLE
Deleting column from treeview in visual design does not update Position

### ISSUE THREAD

**Issue by DGH2112** [JAM-Software/Virtual-TreeView#826] opened 2018-09-08 09:57 UTC
I've just had an instance where I've deleted a column (third from the right) from a TVirtualStringTree in the IDE and when the application loaded the form an index out of range error was raised.

After careful examination of the DFM text file I found that the Position property of the columns to the right of the one I deleted were not updated. I had to manually decrement their Position numbers by one. 

The application then loaded the form without any errors.

The version used was 7.0 with no changes. I was unable to reproduce this with the Advanced demo. If I get time today I'll try and produce an example.

regards
Dave.

**Comment by joachimmarder** [comment] 2018-09-09 07:54
Please respect our guidelines for reporting bugs as stated on the project homepage:

Please include the version you are using. When reporting a bug please include a sample project that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug.

**Comment by joachimmarder** [comment] 2018-12-10 13:21
Since no repro steps for the problem were supplied so far, I am closing this issue.

**Closed as completed by joachimmarder** 2018-12-10 13:21 UTC
Labels: Repro Steps Missing
