### ISSUE TITLE
VT Header draws smudged (see screenshot)

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#248] opened 2015-01-21 13:46 UTC
_From [danielfr...@gmail.com](https://code.google.com/u/108157369915788608871/) on December 19, 2011 22:14:37_

I recall VT's painting to be quite smooth when I used it in D7 (with Mike's releases). Now, the painting, when dragging a column, seems to be really lagging behind, and sometimes when you click on the column header and drag really quickly, you get a smudge (see screenshot). I disabled theme awareness; same problem (speaking of theme awareness, even when it was off, the XP mode was a really nice feature, now gone).

**Attachment:** [vt2.png](http://code.google.com/p/virtual-treeview/issues/detail?id=248)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=248_

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 23, 2014 14:02:39_

Is the problem still there in V5.5.1?

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [ricardo....@gmail.com](https://code.google.com/u/108288369470425248818/) on January 06, 2015 18:48:51_

This fail draw occurs on 5.52 too. When you try to change column order, and mantains cursor in vertical header range the control draws a piece in selececter column color. any solution at this moment?

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on January 08, 2015 10:44:58_

I'm sorry, no solution from me. I personally never worked in this part of the code so far.

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [ricardo....@gmail.com](https://code.google.com/u/108288369470425248818/) on January 08, 2015 16:23:02_

Thanks any way, last thing, do you have any clue where can I start to find this bug?, or can you contact the person that work in this behavior.

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [danielfr...@gmail.com](https://code.google.com/u/108157369915788608871/) on January 09, 2015 04:02:38_

Let me check if this is still the case - will get back to you ASAP.

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [ricardo....@gmail.com](https://code.google.com/u/108288369470425248818/) on January 14, 2015 17:09:41_

Ok, I found a "more or less" solution.
The problem is first capture of the dragging button, in the TVTHeader.HandleHeaderMouseMove make the correct operation, changing DownIndex to NoColumn, and redrawing the header with an Invalidate but it need a direct repaint, not an invalidate, so, the code captures the header button before repaint the button in release state (the WMessage is processed later).

The solution is in TVTHeader.HandleHeaderMouseMove line 12572 in v5.52, you need to add an treview.update after invalidate, then process pending messages before call preparedrag and capture the blue button for background.

Change this ---->

if I > NoColumn then 
   Invalidate(FColumns[I]);

with this  ---->

if I > NoColumn then begin
   Invalidate(FColumns[I]);
   Treeview.Update;
end;

The problem with a lagging draw is not corrected, but that is another problem, slow folow the mouse cursor and a lor of blinking, and seems that text move into dragable button. Now beautiful to see.

**Comment by vincentparrett** [comment] 2015-01-21 13:46
_From [ricardo....@gmail.com](https://code.google.com/u/108288369470425248818/) on January 15, 2015 09:40:55_

This code (draw on drag, this is an incredible control anyway) seems to be very buggy. Another thing with simply solution is when you drag one column not show dragcursor, to solve this, insert Windows.SetCursor(Screen.Cursors[self.DragCursor]); in first line after begin in DoHeaderDragging method.

**Comment by RicardoBer** [comment] 2016-01-19 01:17
At this moment this problem continues, do anyone know something more about this?

**Comment by joachimmarder** [comment] 2016-01-19 09:21
Do you have simple repro steps for this issue with one of the sample projects?

**Comment by RicardoBer** [comment] 2016-01-20 09:54
Yes, it fails always when move any hader tab. For example in advanced demo, four button.
![sin titulo](https://cloud.githubusercontent.com/assets/14173576/12445144/e96d7340-bf62-11e5-92a2-09072824e663.jpg)

Try dragging over header.

I remove that blue piece adding and update on HandleHeaderMouseMove method, but this ugly behavior continues in latest version, any way the drag operation shows lagging and blinking.
The control show good, but not in this case.

**Comment by RicardoBer** [comment] 2016-01-22 21:54
There are another problem with circled arrow icons that paint on the sides of header buttons, they are cropped, some times it's now drawed other ones remain drawed, buf.

**Comment by sanjayssk** [comment] 2016-07-11 04:09
I can't seem to reproduce this problem on my Win 10 and Win 7. The screenshot above where the "Column3" is smudged--was it a VM being used?

**Comment by RicardoBer** [comment] 2016-07-29 02:00
The problem was reproduced on windows 7 ultimate clean installation, not in VM (yes I test on a VM windows 8 and one VM windows XP (I know, XP...). And fail in all of them, persistent error. I compile it with delphi XE7 and XE3.

Only pick column and move it from left to right and viceversa some times and problem arise. If you need that I make more test, please tellme.

Upper capture was with unmodified demo app.

Another one from a vcl styles app.

![image](https://cloud.githubusercontent.com/assets/14173576/17235371/e8f85596-5540-11e6-9cf0-c5b03cad99df.png)

**Comment by sanjayssk** [comment] 2016-08-03 13:09
Please test with the latest commit and confirm that the problem is solved.

**Comment by RicardoBer** [comment] 2016-08-04 01:02
Worst,

![image](https://cloud.githubusercontent.com/assets/14173576/17386941/64b44020-59ef-11e6-9b5b-b8e2c96d06dd.png)

I download latest version from github (thursday 4/08/2016) and the icons seems to be more affected, this time some icons or pices of them appear in others colums headers (look at left of "Localidad").

**Comment by sanjayssk** [comment] 2016-08-04 02:05
The issue is originally about smudged header caption in the first screenshot. Please check if that problem is solved. The problem of icons might be related to different part of the code and may need another solution so it needs to be pushed to another issue.

**Comment by RicardoBer** [comment] 2016-08-04 02:23
Yes, it's exactly the same, capture of demo with last versión of VT

![image](https://cloud.githubusercontent.com/assets/14173576/17388236/1eefbcd4-59fb-11e6-8130-e6d65ba1470c.png)

 drag operation shows lagging and blinking now too.

**Comment by sanjayssk** [comment] 2016-08-04 03:18
Please look again carefully. In the earlier screenshot, the caption of the source "column3" is distorted.
![image](https://cloud.githubusercontent.com/assets/20315846/17389238/e961caec-5a1f-11e6-826f-262e2b3c27cf.png)

In the new screenshot, it's properly aligned. 
![image](https://cloud.githubusercontent.com/assets/20315846/17389252/21502fca-5a20-11e6-8fbf-0c9f46164217.png)

That's the problem that has been solved.

**Comment by RicardoBer** [comment] 2016-08-04 04:15
ok, it is aligned, but continue smudge, blue parts drawing anywhere, draw very laggy, blinking and "eat" the position icons. vincentparrett don't talk anytime about align.

Sorry, but I think there are a serious problem when drag the header, I don't think the align is the worst one.

**Comment by vincentparrett** [comment] 2016-08-04 04:52
FWIW, I am not the original reporter of this issue, my name was added by github because I imported the repo from googlecode.

**Comment by sanjayssk** [comment] 2016-08-04 04:52
It takes several attempts to produce that kind of caption distortion. The fact that it's included in the original screenshot means it was shown as the main problem to be tackled. It stands out in that screenshot.

Let's see what Joachim decides.

It might be better if the issue is broken into multiple parts because there seem to be multiple problems with dragging and the relevant code might be different for each problem. Then the priority can be assigned based on the seriousness as perceived by Joachim. Besides, some of these problems may be unsolvable unless the drag class is redesigned.

**Comment by RicardoBer** [comment] 2016-08-04 05:31
Ok, thanks for your work and for the response, I understand.

**Comment by sanjayssk** [comment] 2016-08-04 07:38
Thank you for your help in testing and for reporting problems.

**Comment by joachimmarder** [comment] 2016-08-04 13:53
> It might be better if the issue is broken into multiple parts

I case the cause and the resolutions are different for the various parts, I vote for separating them. If cause and resolution are similar, we should keep it in a single issue.

**Comment by sanjayssk** [comment] 2016-08-05 06:48
I also found a usage issue for header drop marks. When the dragged column is not going to change position, no drop mark should appear. Currently it does. To recreate, drag a column a little to the left column (below the header). A drop mark still appears on the right of left column header even though the current column will not be dragged. Similar problem with the right drag. Is this correct usage behavior? 

According to me, it shouldn't. No drop mark should appear unless the column is going to change position.  Please give your thoughts on this. Thanks.

**Comment by joachimmarder** [comment] 2016-08-05 07:22
> No drop mark should appear unless the column is going to change position. 

I agree. You may open a separate issue at GitHub for this.

**Comment by sanjayssk** [comment] 2016-08-06 06:22
The dropmark icon drawing problems in this issue are related to a missing function in the TVTHeader class that should have been there similar to UpdateWindowAndDragImage in TBaseVirtualTree. Basically, during a drag, only the drop marks appear or go. At that instant, the above type of function should be used to redraw the changed header into the drag image's backup image to solve the problem. 

Currently what happens is that the backup header image is captured without the drop mark and then restored after the drop mark appears and image is dragged, causing part of the drop mark to disappear.

Will work on that function next.

**Comment by sanjayssk** [comment] 2016-08-17 16:33
I just committed a fix for this header smudge problem. Please test it and let me know whether it works better.

Thanks.

**Comment by RicardoBer** [comment] 2016-08-20 17:33
I download latest version today, and sorry, but worst. 

![image](https://cloud.githubusercontent.com/assets/14173576/17832756/b9a44eea-670a-11e6-920e-31c645d7d862.png)

Blinking is higher and many times background is drawed over drag object. In the image the dragged object is under col 1 header. This behavior doesn't occur in previous version.

I only can say thanks by this control and I hope you forgive me, but I think all  this artifacts are all in one point, the code that draws the dragging object and restore background is buggy.

Some comments above I talk about add an update aften an invalidate, I know, I update entire treview, so I am shooting a fly with a canon, but the problem goes better. I think thak mouse move events capture background before invalidate in mesage queue is procesed, so, background is corrupted.

**Comment by sanjayssk** [comment] 2016-08-22 14:05
I can't see any difference in blinking from previous to this one. The blinking occurs only when the drag goes over a new column. That is same as before. Are you using a VM? I'm not using a VM.

> many times background is drawed over drag object

Whatever I do, I can't recreate that problem. Can you give me steps to recreate the problem shown in the screenshot? Also tell whether you are using a VM.

Thanks.

**Comment by RicardoBer** [comment] 2016-08-22 21:54
Hello, no I'm using an q9550 with ati 6870, Windows 7 64bits, no vm. I tested today in other two pc with windows 7 and one more with windows 8, same problem in all of them. I only catch a column header and displace to the left over other columns. In deed i can only see that works well on windows XP but I read the code and in xp use other mechanism.

Tomorrow I'm goint to prepare a windows 10 machine ( no vm) and test too, i'll send a capture

**Comment by sanjayssk** [comment] 2016-08-24 12:23
OK. I got it now why I'm not seeing the same problems as you. All this time, I have been testing under Windows 10, assuming that it's same underneath as Windows 7, at least for win32 apps. In Windows 10, the fix works quite well and I can't duplicate that problem at all. But after your message, I just tested on an old Windows 7 laptop, and I can duplicate the problem of drag image going under immediately. 

So it seems, Microsoft seems to have done some work under the hood in Windows 10. It's different after all, even for Win32.

Thanks.

**Comment by RicardoBer** [comment] 2016-08-25 12:22
Yes, it behavior it's different depending on windows version. In windows 10 less lagging (many anyway), don't paint behind header, but cut position indicators.

![image](https://cloud.githubusercontent.com/assets/14173576/17968848/420a4a9c-6acf-11e6-8336-4160414abab3.png)

**Comment by sanjayssk** [comment] 2016-09-06 14:04
Well, I have made some major changes to fix this issue. I tested this time on Windows 7 too. I no longer see the blue rectangles, delay and partial drop marks being painted. Please use the latest commit to test the fix and let me know if you still see any problems.

Thanks.

**Comment by sanjayssk** [comment] 2016-09-13 06:51
I'm closing this issue. If you happen to still find any related problem, please open it again. Thanks.

**Closed as completed by sanjayssk** 2016-09-13 06:51 UTC
Labels: Bug, Pull Requests Invited

**Comment by RicardoBer** [comment] 2016-09-13 23:39
I can’t test it, latest build is not installable on Delphi XE7. I open Issue #655

**Comment by joachimmarder** [comment] 2016-09-14 09:21
Sorry, #655 is fixed now.

**Comment by RicardoBer** [comment] 2016-09-14 23:13
Sorry but

---

El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by RicardoBer** [comment] 2016-09-14 23:17
Sorry but the problem continues although only occurs when move the header for some time, it is near to work indeed.

![image](https://cloud.githubusercontent.com/assets/14173576/18533243/d18c7ee8-7ae1-11e6-9567-5eeaf217e2bb.png)

This capture is from just now, with the latest build.

It is much more difficult to reproduce the error, but it is possible now in windows 7.

The position icon is cutoff.

**Comment by sanjayssk** [comment] 2016-09-15 02:10
Thank you for testing. Can you explain what you mean by position icon is cutoff? If you mean the DropMark on the left, it was a bug. Dropmark should not appear if the column is not going to change position. See issue #643. Other than that, please give more details on what problem you see. Thanks.

**Comment by RicardoBer** [comment] 2016-09-15 02:20
No, thanks to you, awesome work,

Ok, In that capture I move the Column 3 between "column" and "Column1" if you look on top of "C" letter of Column 1 you can see a piece of the Dropmark.

**Comment by sanjayssk** [comment] 2016-09-15 02:40
I see now. I saw the problem in painting C but didn't realize it was a drop
mark that was causing it. Thanks for catching that.

**Comment by kong-en-ge** [comment] 2022-11-26 19:18
https://github.com/JAM-Software/Virtual-TreeView/issues/248#issuecomment-174064741
> There are another problem with circled arrow icons that paint on the sides of header buttons, they are cropped, some times it's now drawed other ones remain drawed, buf.

This issue seems to have a simple solution after hours of investigations.
In TVTDragImage.DragTo add the bold line:

> // If moved more than image size then just restore old screen and blit image to new position.
> BitBlt(ScreenDC, FImagePosition.X, FImagePosition.Y, FBackImage.Width, FBackImage.Height,
>   FBackImage.Canvas.Handle, 0, 0, SRCCOPY);
> 
> **GetPixel(ScreenDC, FImagePosition.X, FImagePosition.Y);**
> if ForceRepaint then
>   UpdateWindow(FOwner.Handle);
> 

This looks to be an enforcement of correct access sequence to ScreenDC inside the WinAPI. 
First we restore backup image, then update window to reflect column header changes (this part often skips and causes bad circle icon traces), and then take the updated part to the back buffer.
Any access to ScreenDC content looks to be such an enforcement, and I chose GetPixel since it doesn't change the device state in any way.

**Comment by joachimmarder** [comment] 2022-11-26 19:27
Thanks, I added this line (without testing) to the master branch.
