### ISSUE TITLE
Even if a parent node IsFiltered out, the child nodes are drawn hanging instead of hiding them

### ISSUE THREAD

**Issue by sanjayssk** [JAM-Software/Virtual-TreeView#701] opened 2017-03-13 13:28 UTC
If you take the test program from issue #557 and compile it with the latest version (or even older versions), you will see that it paints hanging child nodes when the parent node has been filtered out. The correct behavior should be that the child nodes of a filtered out parent should not be visible at all.

**Comment by obones** [comment] 2017-03-20 20:39
Well, from what I understand of the initial intent behind Filtered and Visible is precisely that difference:
Visible=False applies to a node and its children while Filtered=True applies to a node only.
So, to me, what you are describing is expected behavior as transpires from various areas in the code itself, dating from ages ago.
But I may also have understood all this incorrectly.

**Comment by sanjayssk** [comment] 2017-03-21 04:31
Thank you for your thoughts. What you say is true for a "flat" grid. In case of a Tree View, it must show a valid tree structure. Hanging children have no meaning in a tree view.

**Screenshot 1**
If you compile the test in #557 with the latest version, you get this view which is clearly invalid. Note that scrollbar is at the top.
![image](https://cloud.githubusercontent.com/assets/20315846/24132581/996b0ab0-0e1c-11e7-9c3d-b05364f77843.png)

**Screenshot 2**
Here is another for a test change I made.
![image](https://cloud.githubusercontent.com/assets/20315846/24132590/b07a5b52-0e1c-11e7-9f68-f564c3285e50.png)

The correct behavior is to show full branch of a visible node even if the parents are filtered out by logic. This behavior is expected of all tree grids for filtering.
Here is a quite recent reference to an angular doc.
[Filtering in a tree](https://angular2-tree.readme.io/docs/filtering)

**Comment by sanjayssk** [comment] 2017-03-21 04:43
Further food for thought:
There are 2 possibilities and that's why this is complicated and is open for discussion.

1) As described in the link above, if a "leaf" node is visible by the filter, make its parent and grandparents visible.
OR
2) If a parent is hidden due to the filter, hide all its children.

I'm trying to make an example to show the uses of both the above scenarios. I think the above cases depend on the type of filter and that makes it more complicated. As far as the solution 1 is concerned, I have already found a simple **fix in SetChildCount and tested it. But since the decision is made at the time of adding nodes, it has to be tested out in other situations too where nodes are added, for example when streaming in or dragging, copying.

Correction: My **solution mentioned above is top-down (scenario 2) as it is in SetChildCount when creating a child. What is needed is a bottom-up solution where the child has to be filtered after its complete initialization and then the visibility of the parents has to be determined.

**Comment by sanjayssk** [comment] 2017-03-21 05:18
Thinking further, it boils down to the meaning of the filter whether it needs a bottom-up or top-down order when evaluating filters for the 2 scenarios above respectively.

Take for example, a program like TreeSize that displays a tree of folders and the folders have 2 attributes--size and a boolean representing whether it is a System folder.

Consider these filters:
Filter 1) Show me all folders greater than 100 MB. Whether you go top-down or bottom-up there will be no difference in the result. This is so because the size of a parent folder is always more or equal to the child.

Filter 2) Show me all folders less than 100 MB. Here, scenario 1 will apply and you must go bottom-up because you need to show all the folders, even those at leaf level, if they are less than 100 MB. For this, parents greater than 100 MB must be shown if required.

Filter 3) Show me all the System folders. If you think about it, this will need a bottom-up approach because a system folder might be buried underneath a normal folder.

All the examples above show that bottom-up approach (scenario 1) always works. But there might be a situation where you must go top-down in order to show correct results where a bottom-up order will give a wrong result. Unfortunately, I can't think of a real world example that demonstrates this. If you can find something like that, this specification becomes more complicated. It means that along with the filter, whether the filter is to be evaluated top-down or bottom-up also needs to be specified for a tree view.

**Comment by joachimmarder** [comment] 2017-03-21 07:50
> As described in the link above, if a "leaf" node is visible by the filter, make its parent and grandparents visible.

I see one problem here: If you make a leaf node visible, and this node has siblings that are not visible, and the parent is not visible, will it be always correct to change the visibility of the parent automatically? I don't think that kind of automatism will always fit, but the developer still can do that.

**Comment by joachimmarder** [comment] 2017-03-21 07:54
> So, to me, what you are describing is expected behavior 

@obones: Would you really say that Screenshot2 shows a desirable and consistent state?

> as transpires from various areas in the code itself, dating from ages ago.

Sorry, but this is a weak argument. Many things were not OK and needed to be changed after I took over the project, often just because no one took care of. We should aim at doing it right for the majority of the developers, not aim at simply doing it like it was always done.

**Comment by obones** [comment] 2017-03-21 08:32
No, I'm not saying Screenshot 2 is nice, and that's why I avoid filtering in trees where I only use the visible property.
I mean, if filtering was to be changed to what is expected here, what would be the point of having both filter and visible?
But if that can be done in a way that makes everyone happy, then I'm all for it, it's just that I doubt it's easily feasible.

**Comment by joachimmarder** [comment] 2017-03-21 16:39
>  if filtering was to be changed to what is expected here, what would be the point of having both filter and visible?

You can toggle the visibility of filtered nodes on and off in a VT control changing a simple flag and without iterating all nodes (`toShowFilteredNodes`). 

But I agree in one point: I would never have voted for having both possibilities, but that was not my decision and it was made long ago. Since removing one possibility would most likely not make everyone happy, we need to discuss and decide what is the desired state for filtered nodes with non-filtered sub-nodes.

**Comment by the-Arioch** [comment] 2017-03-23 10:18
...can it be arranged that "Open for Discusssion" new issues would get announced in the maillist, to tell them apart from mundane issues/comments stream ?

PS. DiscuSSion :-D

**Comment by joachimmarder** [comment] 2017-09-10 06:43
After half a year with no new comments I decided to keep the current state and therefore close this issue as invalid.

**Closed as completed** 2017-09-10 06:44 UTC
Labels: Invalid, Open for Discussion
