### ISSUE TITLE
GetHitTestInfoAt in OnGetImageIndex resulting in EStackOverflow

### ISSUE THREAD

**Issue by IgitBuh** [JAM-Software/Virtual-TreeView#732] opened 2017-10-03 16:14 UTC
In my VirtualStringTree I have some columns with icons. I would like to change the icon when the mouse cursor is pointing at them. I thought it's an easy task, but when I use GetHitTestInfoAt in OnGetImageIndex I get an EStackOverflow.
My code reduced to the basic problem is this:
```
procedure TForm1.VstGetImageIndex(Sender: TBaseVirtualTree; Node: PVirtualNode; Kind: TVTImageKind; Column: TColumnIndex; var Ghosted: Boolean; var ImageIndex: TImageIndex);
var
  P: TPoint;
  HitInfo: THitInfo;
begin
  P := Vst.ScreenToClient(Mouse.CursorPos);
  Vst.GetHitTestInfoAt(P.X, P.Y, True, HitInfo);
  [...]
end;
```
Am I doing something wrong or is this a bug? Any suggestions for a workaround?

**Comment by joachimmarder** [comment] 2017-10-08 15:01
Please follow the rules for submitting bug reports on the project homepage. Especially include the version of VTV that you are using and a sample project that allows to reproduce the issue. A call stack would be interesting here too.

**Comment by joachimmarder** [comment] 2017-10-08 15:05
> Am I doing something wrong or is this a bug? 

In order to fill `THitInfo.HitPositions` correctly, `GetHitTestInfoAt()` needs to know whether a node has an image or not, and which dimensions it has. So I'd say this is not a bug.

> Any suggestions for a workaround?

You can try `GetNodeAt()`.

**Comment by IgitBuh** [comment] 2017-10-08 17:50
> Especially include the version of VTV that you are using 

It's the latest 6.7. Sorry for not mentioning it. But I tried it out on an old system with an older VTV as well with the same result.

> and a sample project that allows to reproduce the issue.

I thought I did that... Two lines of code are enough to reproduce it.

> You can try GetNodeAt()

That doesn't tell me at which icon/column the cursor is. I'd like to change the icon, when the user points at it.

**Comment by joachimmarder** [comment] 2017-10-08 19:08
> I thought I did that... Two lines of code are enough to reproduce it.

We have these rules for good reason. In many cases the posted code fragment turned out to be not sufficient to reproduce the problem. If you take the time to read our rules, you will notice that it is also OK to describe how to modify one of our sample projects. That might be a good alternative in a case like this.

> That doesn't tell me at which icon/column the cursor is. 

How about using `TVirtualTreeColumns.ColumnFromPosition()`?

**Comment by joachimmarder** [comment] 2017-10-08 19:18
I don't think that `GetHitTestInfoAt()` can do its job as designed without having knowledge about the used icon. So I am closing this issue as invalid.

**Closed as completed** 2017-10-08 19:18 UTC
Labels: Invalid
