### ISSUE TITLE
Access Violation in Event OnGetText() while clearing the Header Columns

### ISSUE THREAD

**Issue by guckinsland** [JAM-Software/Virtual-TreeView#621] opened 2016-04-27 12:00 UTC
Hi together,

if Nodelist is not empty and the Method Header.Columns.Clear() ist called, then OnGetText() Event ist firered serveral times. In OnGetText() the Column Parameter is -1 and node is not nil, also GetNodeData() retrieves a not nil Pointer. Unsing the NodeData raises sometimes an Access Violation Error.
If Nodelist is cleard before the Columns are cleard solves the issue.

Seames, that OnGetText() ist fired in wrong place and with illegal Data.

Regards,
  Klaus

**Comment by joachimmarder** [comment] 2016-04-27 17:45
Which version of VTV are you using?

> Seames, that OnGetText() ist fired in wrong place and with illegal Data.

I am almost sure that this is not the case. Typically the problem is that that the data assigned to the node data has been freed before the node was removed from the control.

I had similar issues in my projects, especially when I start using parallel processing using threads. Handling the lifetime is sometimes difficult in multithreaded scenarios, this is why I use ref-counted TInterfacedObjects meanwhile.

In any case we will need a sample projects hat replicates the problem describes in this issue.

**Comment by guckinsland** [comment] 2016-04-27 18:45
Hi, I'll post the Version tomorrow when I'm on Work.
I'ts right: NodeData is probably freed when I call Columns.Clear().
But why gets the OnGetText() notification fired in this procedure, it's called to clear the nodes, not to Update the Treenodes?

Regards, Klaus

**Comment by joachimmarder** [comment] 2016-04-27 19:02
> But why gets the OnGetText() notification fired in this procedure,

Please post the call stack of the exception.

**Comment by joachimmarder** [comment] 2016-04-27 19:05
>  I call Columns.Clear() [...]
> it's called to clear the nodes

OK: Columns.Clear() is supposed to clear the columns, not the nodes. A treeview without columns is still supposed to display a tree and will call OnGetText.

**Closed as completed by joachimmarder** 2016-04-27 19:05 UTC
Labels: Invalid
