### ISSUE TITLE
Activate option toAutoHideButtons by default, so that empty nodes by default do not show a +/- button

### ISSUE THREAD

**Issue by MHumm** [JAM-Software/Virtual-TreeView#1086] opened 2022-02-11 14:04 UTC
Given a VST containing a node and a subnode. The node displays a + button for expanding/displaying the sub node. It even displays that indicator when the sub node has no vsVisible set in states and thus is not visible. Collapsing/uncollapsing does not make sense in that scenario.  Attached is a demo application showing this behavior. Run it and click the test button.
[VSTInvisible.zip](https://github.com/JAM-Software/Virtual-TreeView/files/8049131/VSTInvisible.zip)

**Comment by joachimmarder** [comment] 2022-02-14 19:55
This is more or else a duplicate of #717. You need to set the option `toAutoHideButtons` to get the behavior you want. If you agree, I will rephrase this issue to set this option as default.

**Comment by MHumm** [comment] 2022-02-15 08:28
Yes, I agree with rephrasing this and I guess changing that default would make sense. I guess the current default is not really what most developers would expect.

**Comment by MHumm** [comment] 2022-04-05 13:06
I'm of course for getting this implemented, but of course I'm biased on this ;-)

**Closed as completed** 2023-03-12 21:11 UTC
Labels: Enhancement, Breaking Change, Open for Discussion
