### ISSUE TITLE
Occasional Access Violation in GetDisplayRect

### ISSUE THREAD

**Issue by romankassebaum** [JAM-Software/Virtual-TreeView#678] opened 2017-01-03 14:13 UTC
From time to time I'm getting an access violation in TBaseVirtualTree.GetDisplayRect. The reason seems to be that Temp.Parent is nil so that a call to Temp.Parent.States is impossible.

The version of the VTV is  6.4.1.

**Comment by romankassebaum** [comment] 2017-01-04 01:33
Here is the callstack:
exception class    : EAccessViolation
exception message  : Zugriffsverletzung bei Adresse 00000000025D6EB4 in Modul 'Test.exe'. Lesen von Adresse 000000000000000A.

main thread ($13d4):
025d6eb4 +0f4 Test.exe     VirtualTrees   26979 +19 TBaseVirtualTree.GetDisplayRect
025daa25 +045 Test.exe     VirtualTrees   29807  +3 TBaseVirtualTree.InvalidateNode
025e7aad +01d Test.exe     VirtualTrees   34582  +1 TCustomVirtualStringTree.InvalidateNode
025e588d +02d Test.exe     VirtualTrees   33728  +2 TCustomVirtualStringTree.SetText
025e4298 +078 Test.exe     VirtualTrees   33206  +6 TStringEditLink.EndEdit
025c6729 +039 Test.exe     VirtualTrees   19934  +2 TBaseVirtualTree.DoEndEdit
025e37e7 +127 Test.exe     VirtualTrees   32947 +23 TVTEdit.WMKeyDown
00410b3e +03e Test.exe     System                   TObject.Dispatch
0078c913 +383 Test.exe     Vcl.Controls             TControl.WndProc
007937c2 +8e2 Test.exe     Vcl.Controls             TWinControl.WndProc
00792a0a +02a Test.exe     Vcl.Controls             TWinControl.MainWndProc
005e57b3 +023 Test.exe     System.Classes           StdWndProc
779998bd +000 USER32.dll                            DispatchMessageW
009317af +12f Test.exe     Vcl.Forms                TApplication.ProcessMessage
00931823 +013 Test.exe     Vcl.Forms                TApplication.HandleMessage
00931c8f +0ef Test.exe     Vcl.Forms                TApplication.Run
03b54e61 +251 Test.exe     Test.Run          69 +35 TTestRun.Execute
03b553f5 +015 Test.exe     Test            3156  +1 initialization
778759cb +00b kernel32.dll                          BaseThreadInitThunk

**Comment by joachimmarder** [comment] 2017-01-04 10:32
It makes no sense that `Temp.Parent` is `nil` without previously `Temp` having the value of `FRoot`, which is the exit condition of the loop in `GetDisplayRect()`.

I tested if deleting the node which is currently edited could cause this error, but this worked fine.

We could add another exit condition `Assigned(Temp)` but this would only cure the symptom and does not fix the root cause, which seems to be some inconsistency in the tree nodes.

**Comment by romankassebaum** [comment] 2017-01-04 17:53
The application is working for many years. With moving to Delphi Berlin I updated the VTV. From this time I'm receiving the AV.

Modifying the line

      if not (vsVisible in Temp.States) or not (vsExpanded in Temp.Parent.States) then
        Exit;

to

      if (Temp = nil) or not (vsVisible in Temp.States) or (Temp.Parent = nil) or not (vsExpanded in Temp.Parent.States) then
        Exit;

solved the issue for me.

**Comment by joachimmarder** [comment] 2017-01-04 19:47
Without repro steps there is not much else we can do here, so I will use this fix, although it won't fix the root cause.

**Closed as completed** 2017-01-04 19:50 UTC
