### ISSUE TITLE
Incorrect focus rectangle drawing when linking the VT to property editors and using toUseExplorerTheme

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#453] opened 2015-01-21 14:05 UTC
_From [stevecod...@gmail.com](https://code.google.com/u/108861890102507120184/) on July 25, 2014 23:39:11_

If toUseExplorerTheme is true, and a property editor is linked to the VT (ie.: a TEdit control), upon clicking on the editor (when the EditNode function is called) the inactive focus rectangle in the background of the editor's cell will be erased (see attached picture).

Interestingly, if you hover the mouse over the node in question the themed hot track rectangle is drawn properly.

I've located the line of the problem, and provided a workaround for VT version V5.4.1.

Note that something is coloring the background of the inactive selection rectangle to a lighter (whiter) color and I've not been able to figure out what's doing it, so I've included two lines in the code which are while a little bit ugly, still make it work properly (no coloring).

If somebody who is more experienced with VT than me can come up with a more elegant solution I'd appreciate it.

Please consider including either this or an enhanced fix in the next release.

**Attachment:** [ScBug2.png VirtualTrees.pas](http://code.google.com/p/virtual-treeview/issues/detail?id=453)

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=453_

**Comment by vincentparrett** [comment] 2015-01-21 14:05
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on July 28, 2014 14:13:53_

Are you familiar with creating patch file, e.g. using TortoiseSVN? A patch file would be very much appreciated: It is small, you don't need to apply it to a certain revision and you can easily see the changes made.

**Comment by vincentparrett** [comment] 2015-01-21 14:05
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on August 13, 2014 13:26:50_

I just created a step-by-step tutorial on how to create a patch file: https://code.google.com/p/virtual-treeview/wiki/CreatePatch

**Comment by joachimmarder** [comment] 2017-05-26 09:32
Never received sample project or patch from reporter. Files were lost when importing from Google Code. Issue might have been fixed in the meantime. So I am closing this issue. If the problem is still there, please open an new issue with a sample project or repro steps for the Advanced sample project.

**Closed as completed by joachimmarder** 2017-05-26 09:32 UTC
Labels: Bug
