### ISSUE TITLE
Header columns hint doesn't work

### ISSUE THREAD

**Issue by LukaszDemczuk** [JAM-Software/Virtual-TreeView#958] opened 2020-03-25 21:45 UTC
In demos folder is project **Interfaces**.
I'm trying to add hint for header columns.
In the method TEventPresenter.setup:
- for all columns I added some hint,
- to header options I added: hoShowHint,
- I set ShowHint for component  fVST,
- I set ShowHint for FormModelView

It still not working. What should I do more?

**Comment by joachimmarder** [comment] 2020-03-28 10:07
I guess the reason is issue #728. Run the `Advanced` demo project and see the Align demo for a working example. Because of issue #728, a node's hint needs to be displayed first sot that a column hint appears.

**Comment by joachimmarder** [comment] 2020-03-28 13:14
I modified the `Interfaces` demo project so that it shows column hints. However, this will work only if the Virtual TreeView control showed a node hint before. To achieve this, make one column small so that text is cut off, the hover over the text until a tooltip with the full text pops up, then hover over the first or second column.

So this seems to be a duplicate of #728.

**Comment by LukaszDemczuk** [comment] 2020-03-30 06:01
You've set the Text property of the second column twice.
Just click on end of first column (on the line). After it, hints are shown.

**Comment by joachimmarder** [comment] 2020-03-31 08:54
> You've set the Text property of the second column twice.

Oops, yes, it's corrected now.

> Just click on end of first column (on the line). After it, hints are shown.

True, but a normal user won't do that. And it stops working once another hint was shown. To demonstrate this, I added a hint to the left button. Still, this is a duplicate of #728 which is why I am going to close this issue.

**Closed as completed** 2020-03-31 08:54 UTC
Labels: Duplicate
