### ISSUE TITLE
Vertical scroll bug

### ISSUE THREAD

**Issue by arctic-sun** [JAM-Software/Virtual-TreeView#1183] opened 2023-03-19 00:53 UTC
demo video:
![a](https://user-images.githubusercontent.com/109481884/226147874-04564aa9-ed3b-40f8-b7ba-7c4af3947d68.gif)

src of the demo:
[test_src.zip](https://github.com/JAM-Software/Virtual-TreeView/files/11009958/test_src.zip)

**Comment by joachimmarder** [comment] 2023-03-19 18:56
**Repro Steps**
- Run attached sample project with V7.6.4
- Press Shit+Ctrl+NumPad- to collapse the entire tree
- Press the button
- Expand the topmost node
- Scroll to the bottom using the scrollbar 

**Expected**
You see node I:20

**Actual**
You see node I:15

**Comment by joachimmarder** [comment] 2023-03-22 21:07
This issue is similar to issue #1000. Reason for the problem is that the font size is changed while nodes are already present in the tree, their `NodeHeight` and `TotalHeight` is not updated.

A workaround is to make this call in addition: 

`VirtualStringTree1.ScaleNodeHeights(SpinEdit1.Value, OldFontSize);`

`TBaseVirtualTree.ChangeScale()`does this call automatically, but for a changed font size, there is no good trigger: `TBaseVirtualTree.FontChanged()` is called way too often.

Any further ideas from the community?

**Comment by joachimmarder** [comment] 2023-04-01 12:08
Since there is a good workaround but no good fix, I am closing this issue. Pull requests will still be accepted.

**Closed as completed by joachimmarder** 2023-04-01 12:08 UTC
Labels: Pull Requests Invited
