### ISSUE TITLE
When a node is MultiLine it initialy renders it only as Singleline until the mouse is moved over the node

### ISSUE THREAD

**Issue by raketenwurm69** [JAM-Software/Virtual-TreeView#994] opened 2020-10-09 14:31 UTC
This only happens when there is a tree structure (parent->child) to expand. It does not happen when there is only one level of nodes.

![image](https://user-images.githubusercontent.com/32537343/95597117-88931700-0a4e-11eb-8773-27becc9618e8.png)

![image](https://user-images.githubusercontent.com/32537343/95597195-9d6faa80-0a4e-11eb-83b6-360f8f4f5c7c.png)

I am using the latest version from the zipped repo (VirtualTrees.pas is from 26.09.2020). The problem was also present in v7.3 of VTV.

**Comment by raketenwurm69** [comment] 2020-10-09 15:44
UPDATE: 
I found out that in DoMeasureItem() the method ComputeNodeHeight(Canvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex; S: string) has an optional 4th parameter. When I set it to the text that is supposed to be in the multiline column, it works fine. If I leave it empty it tries to get the string from the node and ends up getting only "node" instead of the correct column content.

**Comment by joachimmarder** [comment] 2020-10-09 18:54
Please respect our guidelines form the project homepage: When reporting a bug please attach a sample project as ZIP-file that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. Please follow best practices for good bug reports.

If you already have a solution, please supply a patch file or make a pull request. If you used a previous version that did not have the bug, please include this version number in your report.

**Comment by joachimmarder** [comment] 2020-10-09 18:55
>  ends up getting only "node" instead of the correct column content.

I would have expected to see "node" in your screenshot than.

**Comment by joachimmarder** [comment] 2020-10-25 22:16
Closing this issue due to missing repro steps or pull request.

**Closed as completed by joachimmarder** 2020-10-25 22:16 UTC
Labels: Repro Steps Missing
