### ISSUE TITLE
Header is not auto-scaled on form creation

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [JAM-Software/Virtual-TreeView#913] opened 2019-07-17 12:54 UTC
There's `TVTHeader.FontChanged` method where header is resized according to font and columns properties. But when component is being read from a form resource this method is only called on parent font change (when there's no columns yet) so header gets its height as large as `TextHeight('Q')` without any spacing so it looks pretty small for column captions.
I see two possible workarounds: explicitly call `FontChanged` after loading columns (_con_: quite not logical) or use a default Spacing constant that would be used if there's no columns at the moment (_con_: probably user could want tight header)

**Comment by joachimmarder** [comment] 2019-07-22 21:02
Can this be easily reproduced with one of the included sample projects?

**Comment by Fr0sT-Brutal** [comment] 2019-07-23 07:11
It can be easily reproduced on a trivial empty project (for the sake of clean experiment).
```
unit Unit2;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, VirtualTrees;

type
  TForm2 = class(TForm)
    VirtualStringTree3: TVirtualStringTree;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form2: TForm2;

implementation

{$R *.dfm}

end.
```
```
object Form2: TForm2
  Left = 0
  Top = 0
  Caption = 'Form2'
  ClientHeight = 199
  ClientWidth = 339
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 120
  TextHeight = 16
  object VirtualStringTree3: TVirtualStringTree
    Left = 65
    Top = 30
    Width = 200
    Height = 100
    Header.AutoSizeIndex = 0
    Header.Options = [hoColumnResize, hoDrag, hoShowSortGlyphs, hoVisible]
    StyleElements = [seFont, seClient, seBorder]
    TabOrder = 0
    Columns = <
      item
        Position = 0
        Text = 'Test column Qq'
        Width = 123
      end>
  end
end
```
![image](https://user-images.githubusercontent.com/1469388/61689745-6ec5c100-ad30-11e9-851a-cc9a0f1d3f6f.png)

But if we add
```
procedure TForm2.FormShow(Sender: TObject);
begin
  VirtualStringTree3.Header.Font.Style := [fsStrikeOut];
end;
```
so that FontChanged is called when columns exist, we get the resize. It's not enough though but at least it got called.

![image](https://user-images.githubusercontent.com/1469388/61690380-d8929a80-ad31-11e9-8449-0f1e5a7b91c3.png)

Btw, I have 120 dpi on my system

**Comment by joachimmarder** [comment] 2019-07-28 15:07
Sorry, but I was unable to reproduce that `FontChanged()` is _not_ called (Windows 10, Delphi 10.3). 

If `FontChanged()` is not called but the screen is scaled at 125% like in your case, `ChangeScale()` should be called. So it could make sense to extract the relevant code from `FontChanged()` to a new method `AutoScale()` and call this also from `ChangeScale()`.

Could you please check if the latest code, which contains this change, fixes the issue?

**Comment by Fr0sT-Brutal** [comment] 2019-08-22 15:43
Joahim, looks better now but not exactly. Check this out: set breakpoint to `TVTHeader.AutoScale` on the line `lMaxHeight := Max(lMaxHeight, Columns[I].Spacing);` and launch a project. There will be no break as `AutoScale` is only got called when there are no columns. But if we add `TVTHeaderHack(VirtualStringTree3.Header).AutoScale;` to `TForm2.FormCreate` - breakpoint will trigger.
This is not about only scaling, f.ex. `Column.Spacing` doesn't gets estimated.
See the project attached, I tested it with 10.1 and default system DPI.
[VTVTest.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/3530826/VTVTest.zip)

One more issue is odd text height calculation in `TVTHeader.AutoScale`.
If we have default `Column.Spacing = 3` and `Font.Size = 9`, `Canvas.TextHeight('Q')` will be `18` (on 120 DPI). But if we measure the header in run-time, text will be much smaller!

![image](https://user-images.githubusercontent.com/1469388/63528499-bc8a4080-c50b-11e9-935f-a7d4814ea477.png)

**Comment by joachimmarder** [comment] 2019-08-23 19:43
> Check this out: set breakpoint to TVTHeader.AutoScale on the line lMaxHeight := Max(lMaxHeight, Columns[I].Spacing); and launch a project. There will be no break

I cannot confirm that:
![grafik](https://user-images.githubusercontent.com/10615289/63619411-e5cfcd00-c5ee-11e9-8b0d-749b7ee57418.png)

But this was Delphi 10.3.2. I don't have a Delphi 10.1 at hand.

**Comment by joachimmarder** [comment] 2019-08-23 19:45
> Canvas.TextHeight('Q') will be 18 (on 120 DPI). But if we measure the header in run-time, text will be much smaller!

I noticed such discrepancies at other occasions, it is not Virtual-TreeView specific but seems to be a bug in TCanvas.TextHeight() or the underlying Windows API function.

**Comment by joachimmarder** [comment] 2019-11-25 20:27
Possibly related to high-dpi bugs in Delphi 10.1, no further update from reporter, therefore closing this issue for now.

**Closed as completed by joachimmarder** 2019-11-25 20:27 UTC
Labels: Repro Steps Missing
